version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINER_PHPMA_NAME}
    restart: always
    volumes:
      - /sessions
    environment:
      PMA_ARBITRARY: 1
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${NETWORK}
